namespace types.deity {
    // aspects define properties of a deity
    public enum DeityAspectEnum {
        // elements
        FIRE,
        WATER,
        AIR,
        EARTH,
        THUNDER,
        LIGHT,
        DARKNESS,
        // POISON,
        // ROT,
        // TIME,
        
        // professions
        SMITHING,
        MEDICINE,
        FARMING,
        ENGINEERING,
        TRADING,
        BREWING,
        HUNTING,
        
        // TRAVELING,
        // ART,
        // PERFORMANCE,
        // DEATH, 
        // LIFE,
        // CHAOS,
        // ORDER,
        // CHANGE,
        // STASIS,
        // LUCK, GAMBLING,
        // FATE,
        // KNOWLEDGES, WISDOM, LOGIC,
        // LOVE,
        // WEALTH,
        // DISEASE,
        // SECRETS, KNOWLEDGE,, 
        // FEAST, COOKING,
        // HUNGER,
        // PAIN,
        // WAR,
        //
        // WINTER,
        // AUTUMN,
        // SPRING,
        // SUMMER,
        //
        // DAY, 
        // NIGHT,
        // DAWN, 
        // DUSK,
        // TWIGHLIGHT,
        // RAIN, 
        // STORM,
        // BLIZZARD,
        // DRAUGHT,
        // WIND,
        // FOG,
        // COLD,
        // SEAS,
        // RIVERS, LAKES,
        // MOUNTAINS,
        // DESERTS,
        // SWAMPS,
        // FORESTS,
        // TREES,
        // VAMPIRISM,
        // RESURRECTION,
        // DEMONS,
        // KILLING,
        // ENSLAVING,
        // SUN,
        // MOON,
        // STARS,
        // JUSTICE,
    }
}